import { Geist, Geist_Mono } from "next/font/google";
import { Kanit } from 'next/font/google';
import "./globals.css";
import Navbar from '../src/components/navbar.js';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kanit = Kanit({
  weight: ['300', '400', '600', '700', '800'], // เลือกน้ำหนักฟอนต์ที่ต้องการใช้
  subsets: ['thai', 'latin'], // สำคัญมากเพื่อรองรับภาษาไทย
  variable: '--font-kanit', // ตั้งชื่อตัวแปร CSS เพื่อใช้งานใน Tailwind
});


export const metadata = {
  title: "Veggie Vision",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.className} >
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
